sudo: required
services:
  - docker

before_install:
  - docker build -t mydockertrial/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mydockertrial/react-test npm test -- --coverage

after_success:
  - docker build -t mydockertrial/multi-client ./client
  - docker build -t mydockertrial/multi-nginx ./nginx
  - docker build -t mydockertrial/multi-server ./server
  - docker build -t mydockertrial/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  # Take these images & push them to docker hub
  - docker push mydockertrial/multi-client
  - docker push mydockertrial/multi-nginx
  - docker push mydockertrial/multi-server
  - docker push mydockertrial/multi-worker